### ISSUE TITLE
Object viewer's search feature not searching animation's names from any WillowAnimDefinitions.

### ISSUE THREAD

**Issue by Zazk0u** [BLCM/OpenBLCMM#32]
![Capture d’écran 2023-06-24 181757](https://github.com/BLCM/OpenBLCMM/assets/72308078/eddb01bc-f071-483e-9741-707ded39706b)
![Capture d’écran 2023-06-24 181810](https://github.com/BLCM/OpenBLCMM/assets/72308078/1f47deec-feb2-488a-8ef9-54c2992c3e76)
![Capture d’écran 2023-06-24 182055](https://github.com/BLCM/OpenBLCMM/assets/72308078/11175833-34cd-47fb-a5b6-367862b1595d)

**Comment by apocalyptech** [comment]
Hello!

Sorry it's taken so long to get to this; looking into it now!  Though, I don't seem to be able to reproduce it:

![screenshot-2023-07-15-00_24_06](https://github.com/BLCM/OpenBLCMM/assets/443343/bdbb7d27-96b1-49c8-8fa2-3b2299378e15)

What data version are you using?  (Can find that in Help -> About.)  I assume you're on 1.3.3 and not one of the prerelease versions of this?

**Comment by apocalyptech** [comment]
Huh!  Okay, so was looking at this again, and I actually *was* able to reproduce it this time, which threw me through a bit of a loop.  I think what's happening is that somehow the set of categories to search isn't getting properly updated when you initially launch the app.  But then going in to *change* the selected categories ends up making things work again.  I noticed that there wasn't the telltale super-slow bit where the progress bar chews through Static Mesh stuff, for instance.  Hopping into settings, toggling those off and on, and then searching again caused the results to come back just fine.

Another point of data, another instance that trips this up is:

`AnimName=Melee` should pull up `SpecialMove_WeaponAction'GD_Siren_Streaming.Anims.WeaponAnim_Melee'`

... but doesn't, until you've fiddled with the category selection in the settings.  Weird.

Anyway, at least I can reproduce it, in the end.  :)

**Comment by apocalyptech** [comment]
Okay, yep, so this should be taken care of in `next`, for inclusion in v1.4.0 (whenever that comes out).

The base issue was that BLCMM wasn't actually "applying" your data category selections on startup.  The preferences were saved properly and would look fine when you go into the settings, but until you actually fiddled with anything on that dialogue, the selections would always act like they were at their defaults.  That's basically why I thought I couldn't reproduce this stuff -- I'd go in to make sure everything was checked before testing, and viola, there was the data.  Anyway, should be sorted now!
