### ISSUE TITLE
Crash when unexpected files in backup folder

### ISSUE THREAD

**Issue by apple1417** [BLCM/OpenBLCMM#33]
From the support server

![log](https://cdn.discordapp.com/attachments/909192016653590568/1122080949824393247/rn_image_picker_lib_temp_5039ed44-545f-4531-b0eb-1b349e43b3c7.jpg)
[i.e. here](https://github.com/BLCM/OpenBLCMM/blob/main/src/blcmm/utilities/AutoBackupper.java#L65)

![backup folder contents](https://cdn.discordapp.com/attachments/909192016653590568/1122083292678729789/rn_image_picker_lib_temp_0ac75fdf-54cb-4013-b235-c0f43ce95ff9.jpg)

Deleting the new folder fixed it

**Comment by apocalyptech** [comment]
Eesh, didn't notice this one come in at the time.  Thanks for the report; is fixed up in git and will be in for the v1.4.0 release, whenever that happens.
