### ISSUE TITLE
Option to set GearboxAccountData number

### ISSUE THREAD

**Issue by ZetaDaemon** [BLCM/OpenBLCMM#34]
Offline helpers (https://bl-sdk.github.io/mods/OfflineHelpers/) requires changing GearboxAccountData_1 to GearboxAccountData_0 if you use forced offline mode, would be handy to have an option for this in the dangerous settings tab of blcmm

**Comment by apple1417** [comment]
This should be considered a bug in offline helpers, not in BLCMM.

As a workaround, you can do 
```
set Transient.GearboxAccountData_0 Services (Transient.SparkServiceConfiguration_0)
```

**Comment by ZetaDaemon** [comment]
Good to know.
Wasn't really thinking it was a bug in BLCMM but just it would be a nice to have feature for whatever reason to be able to set the GearboxAccountData number since you can also chose the SparkService for offline hotfixes

**Comment by apocalyptech** [comment]
It's easy enough to add this in, so may as well do it.  Just pushed a commit to add this to the Dangerous Settings tab.  Cheers!
