### ISSUE TITLE
Allow forward / back mouse buttons (Mouse4 / Mouse5) to go forward and back on object explorer pages

### ISSUE THREAD

**Issue by DrBones2** [BLCM/OpenBLCMM#43]
Pls thx

**Comment by apocalyptech** [comment]
Yeah, sounds like a good idea.  The `next` branch has a settings dialog for configuring some mouse behavior, could presumably make use of that to allow user configurability for those as well.  Though the mouse-button-selection widget in there would probably need to be updated to somehow allow *de*selecting a button, in case a user with fewer buttons ends up binding something to next/prev and wants to undo that selection.  At the moment it's just a click-to-set-the-button-you-clicked-with kind of thing...

**Comment by apocalyptech** [comment]
Okay, this should be in there, and configurable via the "Input" settings tab.  (That only exists in the `next` branch; it'll be a part of v1.4.0).  I'll probably have a beta release for testing, prior to an actual release -- once that happens, I'd appreciate if you'd test it out to make sure that the defaults are what you expect for forward/back.  Button numbering's a bit weird and Linux doesn't handle it quite how Windows does.  I've got button 4 assigned to Back and 5 to Forward, by default.  (Those are settable in the options, but it'd be nice to have sensible defaults.)

Cheers!
