### ISSUE TITLE
Double click select stops in the middle of a string

### ISSUE THREAD

**Issue by ZetaDaemon** [BLCM/OpenBLCMM#46]
double clicking on `WeaponBalanceDefinition'GD_Weap_SMG.A_Weapons.SMG_Bandit_2_Uncommon'` only selects `WeaponBalanceDefinition'GD_Weap_SMG.A_Weapons.SMG_Bandit`
double clicking on `WeaponPartListCollectionDefinition'GD_Weap_SMG.A_Weapons.SMG_Bandit:PartList'` only selects `WeaponPartListCollectionDefinition'GD_Weap_SMG.A_Weapons.SMG_Bandit`
would be nice to have it fixed so it would select the whole thing

**Comment by ZetaDaemon** [comment]
The breaking on number behaviour seems to specifically only happen when underscores are involved, which amusingly almost always come together
`GD_Weap_SMG.A_Weapons.SMG_Bandit2Uncommon` will have the entire thing selected no problem
`GD_Weap_SMG.A_Weapons.SMG_Bandit2_Uncommon` selects `GD_Weap_SMG.A_Weapons.SMG_Bandit2`
`GD_Weap_SMG.A_Weapons.SMG_Bandit_2Uncommon` selects `GD_Weap_SMG.A_Weapons.SMG_Bandit`

**Comment by apocalyptech** [comment]
Okay, this should be in place now.  It's not implemented in the *ideal* fashion -- ideally you'd want to find where AWT/Swing defines what a "word" is and alter that, but I wasn't able to track that down.  Instead I've just got a mouse listener which expands the selection if need be.  You can actually see the selection go to its default and then expand if need be.

Anyway, the defined delimiters are actually quite a bit more free than the defaults -- it's more than just allowing numbers now.  I think it works out pretty well, though.
