### ISSUE TITLE
Crash upon changing OE Data settings while OE is mid-search.

### ISSUE THREAD

**Issue by Lilu-VA** [BLCM/OpenBLCMM#50]
**Operating System:**
Windows 11

OpenBLCMM Version: 1.3.3
Java Version: 17.0.6
Java VM: Substrate VM GraalVM 22.3.1 Java 17 CE
Memory Used: 130.3 MB
Memory Max: 13.5 GB
BL2 Data: Loaded, v2023.04.20.01
TPS Data: Loaded, v2023.04.21.01
AODK Data: Not loaded: No jarfiles found for AODK

**Describe the bug**
Crash upon changing OE Data settings while OE is mid-search.

**To Reproduce**
Change OE Data settings while OE is searching

**Additional context**
[log-2023-08-11-085722.log](https://github.com/BLCM/OpenBLCMM/files/12321775/log-2023-08-11-085722.log)

**Comment by apocalyptech** [comment]
Ah, yeah, makes sense.  Should be easy enough to fix up; just gotta have the looping search code make a copy of that var instead of operating on the "live" one.  That way the "real" one can be changed without impacting the running search.

**Comment by apocalyptech** [comment]
Okay, this is fixed on `next`, will be a part of 1.4.0.  Cheers, thanks for the report!
