### ISSUE TITLE
Add a Toggle that removes warning for each time Delete and Replace category with contents warns you about deleting\shuffling functional lines of code.

### ISSUE THREAD

**Issue by AceKuper** [BLCM/OpenBLCMM#51]
Add a Toggle that removes warning for each time Delete and Replace category with contents warns you about deleting\shuffling functional lines of code. Would speed up editing and getting removing useless parts of mods or lines of code.

**Comment by apocalyptech** [comment]
Okay, this should be in place now; new settings are available on the General tab.  Cheers!
