### ISSUE TITLE
Disable\Enable all selected

### ISSUE THREAD

**Issue by AceKuper** [BLCM/OpenBLCMM#59]
Add an option for Right Click to have Enable all selected and Disable All Selected as an option.
A key shortcut for the same functions would also be nice.

Just disable and enable, not a toggle. Since a toggle could introduce issues of keeping track of what got switched to what.

**Comment by apocalyptech** [comment]
Okay, this is in place on the `main` branch now.  It'll be a part of v1.4.1 when that drops, which should probably be by Monday.

I used Ctrl-B for Enable and Ctrl-D for Disable.  The Disable hotkey was a no-brainer, but Enable was a bit trickier.  Ctrl-E is already "Edit", Ctrl-N is "File->New", Ctrl-A does a select-all in the tree.  B seemed Good Enough, though.  Really the app should probably have a fully-fledged key configuration dialog, but that'll be for another day...
