### ISSUE TITLE
Report on categories searched when doing fulltext/refs searches

### ISSUE THREAD

**Issue by AceKuper** [BLCM/OpenBLCMM#62]
The thing i was searching this via Refs
![image](https://github.com/BLCM/OpenBLCMM/assets/60463335/47059335-fed0-465b-a895-aa6b1321a8b4)

But it didn't give me this, till i actually put in inclass:WillowInteractiveObject
![image](https://github.com/BLCM/OpenBLCMM/assets/60463335/824e858e-b63f-4849-8090-b2595c0dd99c)

**SOLVED:**

WillowData Data isn't enabled in setting by default and it's Orange coloured, so i thought it was something nonessential.

**Comment by apocalyptech** [comment]
Yeah, those are colored orange mostly to indicate that they tend to make searching noticeably slower when you enable 'em (and a lot of folks don't actually need to see 'em in the results).  I'll leave this open and flip it over to a feature request, though -- one thing that'd probably make this sort of thing more obvious is to report on which categories were used during the search.  That way if something isn't showing up, there'd be a more obvious hint as to why.  The app does report that when there's *no* results found (just search for a random bit of text to see it); something like that could be added to the top of the list once the results are shown.

So yeah, I'll get that in a bit.  :)

**Comment by apocalyptech** [comment]
Okay, so yeah, added a category report to all searches, once they finish.  Should be in v1.4.1, out within a few days, I expect!

![screenshot-2023-09-03-00_06_49](https://github.com/BLCM/OpenBLCMM/assets/443343/b993897e-cdf2-43f7-88b9-36002b40c23e)
